Repository Prescrypto/RexChain, pull requests merged in 2019-05, with the labels that each got.

#36 Add python linter
  .travis.yml
  README.md
  bin/setup_box.sh
  rexchain/api/exceptions.py
  rexchain/api/tests.py
  rexchain/api/urls.py
  rexchain/api/views.py
  rexchain/blockchain/RSAaddresses.py
  rexchain/blockchain/admin.py
  rexchain/blockchain/behaviors.py
  rexchain/blockchain/helpers.py
  rexchain/blockchain/managers.py
  rexchain/blockchain/models.py
  rexchain/blockchain/querysets.py
  rexchain/blockchain/tests.py
  rexchain/blockchain/utils.py
  rexchain/blockchain/views.py
  rexchain/core/apps.py
  rexchain/core/helpers.py
  rexchain/core/management/__init__.py
  rexchain/core/management/commands/check_poe.py
  rexchain/core/management/commands/clear_cache.py
  rexchain/core/management/commands/update_poe.py
  rexchain/core/management/commands/update_total_medics.py
  rexchain/core/utils.py
  rexchain/manage.py
  rexchain/rexchain/forms.py
  rexchain/rexchain/processors.py
  rexchain/rexchain/settings.py
  rexchain/rexchain/urls.py
  rexchain/rexchain/views.py
  setup.cfg
Labels: Priority: High, Status: In Progress, Type: Enchancement

#40 Update the data ordered function
  rexchain/blockchain/utils.py
Labels: Priority: High, Status: Code Review Needed, Status: QA Needed!, Type: Bug

#39 Porting to python 3
  .travis.yml
  README.md
  Vagrantfile
  bin/install_python3.sh
  bin/setup_box.sh
  requirements.txt
  rexchain/blockchain/behaviors.py
  rexchain/blockchain/helpers.py
  rexchain/blockchain/managers.py
  rexchain/blockchain/utils.py
  rexchain/blockchain/views.py
  rexchain/core/utils.py
  runtime.txt
Labels: Priority: High, Status: Code Review Needed, Status: QA Needed!, Type: Enchancement

#42 Fix transfer data from pr7o
  rexchain/blockchain/managers.py
Labels: Priority: High, Status: Code Review Needed, Status: QA Needed!, Type: Enchancement

#44 Feature/fix ascii json error
  rexchain/blockchain/managers.py
  rexchain/blockchain/views.py
Labels: Priority: High, Status: QA Done
