Repository Prescrypto/RexChain, pull requests merged in 2019-06, with the labels that each got.

#46 Add bandit linter
  .travis.yml
  rexchain/blockchain/helpers.py
  rexchain/blockchain/utils.py
  rexchain/blockchain/views.py
  rexchain/core/utils.py
Labels: Status: Completed, Status: QA Done

#47 remove loggers with public or private keys
  rexchain/api/views.py
  rexchain/blockchain/helpers.py
  rexchain/blockchain/managers.py
Labels: Priority: Low, Status: QA Needed!, Type: Maintenance

#48 Update validation method to be more neutral
  rexchain/blockchain/helpers.py
  rexchain/blockchain/managers.py
  rexchain/core/helpers.py
Labels: Status: Completed
