Repository Prescrypto/RexChain, pull requests merged in 2024-09, with the labels that each got.

#98 Feature/Update libs for redis new version support
  requirements.txt
  rexchain/rexchain/settings.py
Labels: Status: QA Done, done

#99 Feature/update hash id to be indexed
  rexchain/blockchain/behaviors.py
  rexchain/blockchain/migrations/0006_auto_20240911_0002.py
Labels: Status: QA Done, done, migration required

#82 Slight improvement to deploy_migrate.sh script
  bin/deploy_migrate.sh
Labels: Status: Code Review Needed, done

#100 Feature/upgrade django version
  Vagrantfile
  requirements.txt
  rexchain/api/urls.py
  rexchain/blockchain/managers.py
  rexchain/core/management/commands/update_total_by_day.py
  rexchain/rexchain/urls.py
  rexchain/static/css/bootstrap-theme.min.css
  rexchain/static/css/bootstrap.min.css
  runtime.txt
Labels: Status: QA Done, done
